### ISSUE TITLE
Can Locked or Deactivated Customers Still Place Orders?  

### ISSUE THREAD

**Issue by wajahatbashir** [wubinworks/magento2-disable-customer#1]
Hi,  

Thank you for developing and maintaining this module. I have a query regarding its functionality:  

- If a customer account is **locked** or **deactivated** in Magento, does this module prevent the customer from placing an order on the frontend?  
- I want to ensure that locked or deactivated customers cannot proceed to checkout and place an order.  

Could you confirm if this functionality is already supported? Or would I need to enhance the module to include this feature?  

Looking forward to your response!

**Comment by wubinworks** [comment]
@wajahatbashir Thank you for your feedback.
 - First, I need to clarify, **lock** and **deactivate** are provided by Magento core, not this extension. This extension never makes use of **lock** and **deactivate**.  
This extension's feature is to **disable** customer. These words have totally different meanings. _You need to read `README.md` carefully_.
 - A disabled customer has already been forced to logout and cannot login. So yes, the customer cannot place order(in its account).

**Comment by wajahatbashir** [comment]
Thank you, Now I have developed a custom module on base of my requirements. Thanks
